apiVersion: v1
description: "Feast Core: Feature registry for Feast."
name: feast-core
version: 0.25.0
appVersion: v0.9.2
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast-java