name: complete

on: [push, pull_request]

jobs:
  lint-java:
    container: gcr.io/kf-feast/feast-ci:latest
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Lint java
        run: make lint-java

